"""empty message

Revision ID: 4352b6579131
Revises: 2ba22f3a9f75
Create Date: 2020-07-31 14:36:21.387878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4352b6579131'
down_revision = '2ba22f3a9f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('publisher_id')
    )
    op.add_column('books', sa.Column('publisher_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'books', 'publishers', ['publisher_id'], ['publisher_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'publisher_id')
    op.drop_table('publishers')
    # ### end Alembic commands ###
